# Generated by Django 4.1.2 on 2023-02-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_quote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(blank=True, max_length=1512, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
