# Generated by Django 4.1.2 on 2023-02-03 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quote_author_alter_quote_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='author',
            new_name='related_link',
        ),
    ]
