# Generated by Django 4.1.6 on 2023-02-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_author_quote_related_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='related_link',
            field=models.TextField(blank=True, max_length=1512, null=True),
        ),
    ]
