# Generated by Django 4.1.2 on 2023-02-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_freepatent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freepatent',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
